export const Status = {
  action: {},
  active: {},
  disabled: {},
  disabledBottom: {},
  disabledLeft: {},
  disabledNext: {},
  disabledPrevious: {},
  disabledPosition: {},
  disabledRight: {},
  disabledSelection: {},
  disabledTop: {},
  dragged: {},
  filled: {},
  focus: {},
  hide: {},
  open: {},
  readonly: {},
  selected: {},
  switchClock: {},
  switchDate: {},
  turn: {},
  visible: {}
}
